steps:
- name: 'node:18'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    npm install
    chmod +x node_modules/.bin/mocha
    npm test
    if [ $? -eq 0 ]; then
      echo "Testes bem-sucedidos, iniciando deploy..."
      gcloud app deploy 
    else
      echo "Testes falharam, deploy cancelado."
      exit 1
    fi
