#steps:
#  - name: 'gcr.io/cloud-builders/gcloud'
#    args: ['app', 'deploy']
#timeout: '1600s'

steps:
steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']

- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'app'
    - 'deploy'
    - '--version'
    - "canary-$(date '+%Y%m%d%H%M%S')"
    - '--no-promote'

- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'app'
    - 'services'
    - 'set-traffic'
    - 'default'
    - '--splits'
    - "canary-$(date '+%Y%m%d%H%M%S')=10,new-version=90"