steps:
- name: 'node:14'  # Use uma imagem do Node.js
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    npm install
    chmod +x node_modules/.bin/mocha
    npm test

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', '--version', '$COMMIT_SHA', '--no-promote']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'services', 'set-traffic', 'default', '--splits', 'new-version=10', 'existing-version=90']
