#steps:
#  - name: 'gcr.io/cloud-builders/gcloud'
#    args: ['app', 'deploy']
#timeout: '1600s'

steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['config', 'set', 'prefix', '$(npm root -g)']
  
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']


- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'test']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', '--version', '$COMMIT_SHA', '--no-promote']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'services', 'set-traffic', 'default', '--splits', 'new-version=10', 'existing-version=90']

