steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']

- name: 'gcr.io/cloud-builders/chmod'
  args: ['+x', 'node_modules/.bin/mocha']

- name: 'gcr.io/cloud-builders/mocha'
  args: ['--file', 'server.test.js']



