#steps:
#  - name: 'gcr.io/cloud-builders/gcloud'
#    args: ['app', 'deploy']
#timeout: '1600s'

steps:
steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']

- name: 'gcr.io/cloud-builders/npm'
  args: ['test']

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      export CANARY_VERSION="canary-$(date '+%Y%m%d%H%M%S')"
      gcloud app deploy --version=$CANARY_VERSION --no-promote

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud app services set-traffic default --splits "$CANARY_VERSION=10,new-version=90"